/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import model.Categoria;
import dao.CategoriaDAO;
import java.util.Scanner;
import controller.CategoriaController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import views.CategoriaView;

public class FormularioCategoria extends javax.swing.JFrame {

  
    public FormularioCategoria() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        CategoriaCrearBtn = new javax.swing.JButton();
        txtIdCategoria = new javax.swing.JTextField();
        txtnombrecategoria = new javax.swing.JTextField();
        CategoriaLeerBtn = new javax.swing.JButton();
        CategoriaActualizarBtn = new javax.swing.JButton();
        CategoriaEliminarBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbTotalCategorias = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(204, 255, 204));
        jTabbedPane1.setBorder(new javax.swing.border.MatteBorder(null));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        CategoriaCrearBtn.setBackground(new java.awt.Color(255, 204, 0));
        CategoriaCrearBtn.setText("Crear");
        CategoriaCrearBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CategoriaCrearBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CategoriaCrearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaCrearBtnActionPerformed(evt);
            }
        });

        txtIdCategoria.setBackground(new java.awt.Color(204, 255, 255));
        txtIdCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtIdCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdCategoriaActionPerformed(evt);
            }
        });

        txtnombrecategoria.setBackground(new java.awt.Color(204, 255, 255));
        txtnombrecategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtnombrecategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombrecategoriaActionPerformed(evt);
            }
        });

        CategoriaLeerBtn.setBackground(new java.awt.Color(255, 204, 0));
        CategoriaLeerBtn.setText("Leer");
        CategoriaLeerBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CategoriaLeerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CategoriaLeerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoriaLeerBtnMouseClicked(evt);
            }
        });
        CategoriaLeerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaLeerBtnActionPerformed(evt);
            }
        });

        CategoriaActualizarBtn.setBackground(new java.awt.Color(255, 204, 0));
        CategoriaActualizarBtn.setText("Actualizar");
        CategoriaActualizarBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CategoriaActualizarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CategoriaActualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaActualizarBtnActionPerformed(evt);
            }
        });

        CategoriaEliminarBtn.setBackground(new java.awt.Color(255, 204, 0));
        CategoriaEliminarBtn.setText("Eliminar");
        CategoriaEliminarBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CategoriaEliminarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CategoriaEliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaEliminarBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Id.");

        jLabel2.setText("Nombre");

        tbTotalCategorias.setBackground(new java.awt.Color(204, 255, 255));
        tbTotalCategorias.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbTotalCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "CategoriaId", "Nombre"
            }
        ));
        tbTotalCategorias.setSelectionBackground(new java.awt.Color(255, 153, 204));
        jScrollPane3.setViewportView(tbTotalCategorias);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Bienvenido ¿Qué deseas hacer?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CategoriaCrearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CategoriaLeerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CategoriaActualizarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CategoriaEliminarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtnombrecategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(txtIdCategoria)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoriaCrearBtn)
                    .addComponent(CategoriaLeerBtn))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtnombrecategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoriaActualizarBtn)
                    .addComponent(CategoriaEliminarBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );

        jTabbedPane1.addTab("Categoria", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CategoriaEliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaEliminarBtnActionPerformed
       CategoriaController categoria= new CategoriaController();
       categoria.eliminarCategoriaVista(Integer.parseInt(txtIdCategoria.getText()));
    }//GEN-LAST:event_CategoriaEliminarBtnActionPerformed

    private void CategoriaActualizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaActualizarBtnActionPerformed
     CategoriaController categoria= new CategoriaController();
     categoria.actualizarCategoriaVista(Integer.parseInt(txtIdCategoria.getText()), txtnombrecategoria.getText());
    }//GEN-LAST:event_CategoriaActualizarBtnActionPerformed

    private void CategoriaLeerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaLeerBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbTotalCategorias.getModel();
        model.setRowCount(0);
        ArrayList<Categoria> categorias = new ArrayList();
        CategoriaController categoria = new CategoriaController();
        List<Categoria> leer = categoria.leerCategoriasVista();
        categorias.addAll(leer);

        Object columnas[] = new Object[2];
        for(Categoria c : categorias){
            columnas[0]=c.getCategoria_id();
            columnas [1]=c.getNombre();
            model.addRow(columnas);
        }
    }//GEN-LAST:event_CategoriaLeerBtnActionPerformed

    private void CategoriaLeerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoriaLeerBtnMouseClicked

    }//GEN-LAST:event_CategoriaLeerBtnMouseClicked

    private void txtnombrecategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombrecategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrecategoriaActionPerformed

    private void txtIdCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCategoriaActionPerformed

    private void CategoriaCrearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaCrearBtnActionPerformed
        CategoriaController categoria= new CategoriaController();
        categoria.crearCategoriaVista(txtnombrecategoria.getText());
    }//GEN-LAST:event_CategoriaCrearBtnActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CategoriaActualizarBtn;
    private javax.swing.JButton CategoriaCrearBtn;
    private javax.swing.JButton CategoriaEliminarBtn;
    private javax.swing.JButton CategoriaLeerBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbTotalCategorias;
    private javax.swing.JTextField txtIdCategoria;
    private javax.swing.JTextField txtnombrecategoria;
    // End of variables declaration//GEN-END:variables
}
